services:
  - type: web
    name: ubuntu-portfolio
    env: node
    rootDir: .
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: GA_MEASUREMENT_ID
        value: ""
